# Generated by Django 6.0.1 on 2026-01-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
