# Generated by Django 6.0.1 on 2026-01-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('professional', 'Professional'), ('researcher', 'Researcher')], max_length=20, null=True),
        ),
    ]
